### ISSUE TITLE
research suggestions inconsistencies

### ISSUE THREAD

**Issue by r14160** [kurmanka/acis.r#16]
There are inconsistencies in the suggestion mechanism for research claims.

Example user registers, gets no suggestion. Once confirmed and logged in,  the profile page indicates suggestions are waiting (red number). But once "research" is clicked, none are available. Launching a new search makes them available. 

It is not clear whether this affects existing users. It has been observed that the rate of new research claims has decelerated, though.

**Comment by kurmanka** [comment]
Hmm. Here is what I've found. Several columns in the database are normally used to store personal short ids, psid. But for new users (who have not yet confirmed their accounts) there are no psids. So, ACIS stores session id there instead. And the session id has grown in size with the security improvements. These old tables where not updated to reflect this change:
- threads
- rp_suggestions

**Comment by kurmanka** [comment]
i think this should fix the issue for the new registrations. I don't think this will change anything for the existing users.
